"""Voiceover metadata for scenes 01-20.

The text comes from docs/02_video_script.md. Each scene is split into three
segments so cues can be placed at the existing visual pauses without changing
the animation content.
"""

SCENE_01_20_NARRATIONS = {
    1: ("AccuracyFailScene", "scene_01_accuracy_fail.py", 80, [
        "Hãy bắt đầu bằng một nghịch lý. Một model có test accuracy gần 99%.",
        "Dashboard đẹp, loss giảm, validation ổn. Nhưng khi đưa ra ngoài đời, nó vẫn có thể sai trong những tình huống rất bình thường.",
        "Nếu chỉ nhìn một con số, ta dễ tưởng model đã hiểu vấn đề. Nhưng có thể nó chỉ hiểu đúng dữ liệu trong phòng thí nghiệm.",
    ]),
    2: ("FailureMontageScene", "scene_02_failure_montage.py", 70, [
        "Robot hút bụi bị kẹt. Camera bóng đá theo nhầm đầu trọc của trọng tài.",
        "Medical AI trong COVID học nhầm tín hiệu bệnh viện. Hệ thống hỗ trợ lái xe phanh sai vì hiểu nhầm bối cảnh.",
        "Các lỗi này khác domain, nhưng đều gợi ý cùng một chuyện: dữ liệu deployment không giống dữ liệu training.",
    ]),
    3: ("ModelOrDataScene", "scene_03_model_or_data.py", 70, [
        "Phản xạ thường gặp là thêm layer, thêm data, thêm regularization.",
        "Nhưng tutorial nhấn mạnh một góc nhìn data-centric: nhiều model problems thực chất là data problems.",
        "Dữ liệu đến từ đâu, có nhóm nào ẩn bên trong, và khi deployment thì nhóm nào thay đổi?",
    ]),
    4: ("IIDBoxScene", "scene_04_iid_box.py", 80, [
        "Trong thế giới i.i.d., train và test được rút độc lập từ cùng một phân phối.",
        "Tưởng tượng có một chiếc hộp P của X và Y sinh ra samples. Một phần rơi vào train, một phần rơi vào test.",
        "Chúng không giống từng điểm, nhưng giống về luật sinh dữ liệu.",
    ]),
    5: ("TrainTestSplitScene", "scene_05_train_test_split.py", 75, [
        "Ngoài đời, người dùng, thiết bị, bệnh viện, quốc gia, mùa vụ đều có thể thay đổi.",
        "Khi test cloud tách khỏi train cloud, validation cũ không còn đảm bảo.",
        "Model vẫn có thể tự tin, nhưng sự tự tin đó được học từ một thế giới khác.",
    ]),
    6: ("ShiftTaxonomyScene", "scene_06_shift_taxonomy.py", 70, [
        "Distribution shift là tên chung cho nhiều kiểu thay đổi.",
        "Có shift ở input, shift ở tỷ lệ label, và shift ở cơ chế Y theo X.",
        "Nếu không phân biệt loại shift, ta rất dễ chọn sai phương pháp robust.",
    ]),
    7: ("XShiftScene", "scene_07_x_shift.py", 75, [
        "X-shift nghĩa là phân phối của X thay đổi.",
        "Ảnh ban ngày sang ban đêm. Người trẻ sang người già. California sang Puerto Rico.",
        "Quy luật Y theo X có thể vẫn giữ, nhưng model chưa thấy đủ vùng input mới.",
    ]),
    8: ("YXShiftScene", "scene_08_yx_shift.py", 80, [
        "Y theo X shift nguy hiểm hơn vì cơ chế dự đoán thay đổi.",
        "Cùng triệu chứng có thể có ý nghĩa khác ở nhóm tuổi khác. Cùng climate feature ảnh hưởng khác theo crop type.",
        "Cùng occupation có ý nghĩa khác trong hai xã hội. Khi mechanism đổi, một single model có thể không còn đúng.",
    ]),
    9: ("DataSourcesScene", "scene_09_data_sources.py", 70, [
        "Dataset hiện đại thường là kết quả merge nhiều nguồn: hospitals, users, regions, sensors, annotators và periods.",
        "Sau khi merge, file chỉ còn một bảng.",
        "Nhưng nguồn gốc khác nhau vẫn để lại cấu trúc bên trong.",
    ]),
    10: ("PooledIllusionScene", "scene_10_pooled_illusion.py", 75, [
        "Khi mọi điểm bị tô cùng màu xám, ta train như thể chúng đến từ một cơ chế.",
        "Nhưng nếu zoom vào, các clusters có thể tương ứng với bệnh viện, vùng địa lý hoặc nhóm người dùng.",
        "Chúng cũng có thể đến từ những data-generating processes khác nhau.",
    ]),
    11: ("HiddenSubpopulationsScene", "scene_11_hidden_subpopulations.py", 80, [
        "Heterogeneity trở nên quan trọng nhất khi các subpopulations có quan hệ Y theo X khác nhau.",
        "Một đường trung bình có thể fit tệ cả hai nhóm.",
        "Biết sample thuộc nhóm nào không phải metadata phụ; nó có thể là thông tin dự đoán.",
    ]),
    12: ("PipelineViewScene", "scene_12_pipeline_view.py", 70, [
        "Tutorial Part 2 đề xuất nhìn toàn bộ pipeline.",
        "Trước training phát hiện subpopulations; trong training học environments; evaluation đo stability và slices.",
        "Khi deployment, ta cần quy lỗi performance drop cho đúng loại shift.",
    ]),
    13: ("ERMFormulaScene", "scene_13_erm_formula.py", 80, [
        "ERM tối thiểu hóa loss trung bình trên training data.",
        "Công thức quen thuộc này là nền tảng của machine learning hiện đại.",
        "Nhưng chữ quan trọng nhất là average.",
    ]),
    14: ("AverageRiskScene", "scene_14_average_risk.py", 70, [
        "Nếu majority group chiếm 85 phần trăm và accuracy 99 phần trăm, average vẫn đẹp.",
        "Điều đó vẫn xảy ra ngay cả khi minority group chỉ đạt 43 phần trăm.",
        "Trong y tế, tín dụng và tuyển dụng, nhóm nhỏ có thể là nhóm quan trọng nhất.",
    ]),
    15: ("SpuriousCowCamelScene", "scene_15_spurious_cow_camel.py", 80, [
        "Nếu bò thường ở cỏ và lạc đà thường ở sa mạc, ERM có thể học background.",
        "Trên test, bò ở bãi biển có thể bị dự đoán sai.",
        "Đây là spurious correlation: pattern đúng trong training nhưng không ổn định khi environment đổi.",
    ]),
    16: ("DROIntuitionScene", "scene_16_dro_intuition.py", 70, [
        "DRO đổi câu hỏi từ tốt trên training distribution sang tốt trên phân phối xấu nhất.",
        "Phân phối xấu nhất này phải nằm trong một tập phân phối đã chọn.",
        "Model chọn theta, còn adversary chọn Q làm loss cao nhất.",
    ]),
    17: ("UncertaintySetScene", "scene_17_uncertainty_set.py", 75, [
        "DRO cần uncertainty set: mọi distribution Q cách P train không quá rho.",
        "Nếu rho quá nhỏ, shift thật nằm ngoài.",
        "Nếu rho quá lớn, worst-case có thể quá cực đoan.",
    ]),
    18: ("FDivergenceScene", "scene_18_f_divergence.py", 75, [
        "f-divergence so sánh phân phối qua density ratio d Q trên d P.",
        "Trực giác là reweight support đã có: training có thể gồm 70 phần trăm người già và 30 phần trăm người trẻ.",
        "Target có thể đổi tỷ lệ này.",
    ]),
    19: ("WassersteinScene", "scene_19_wasserstein.py", 80, [
        "Wasserstein distance đo chi phí vận chuyển khối lượng xác suất.",
        "Nó không chỉ hỏi trọng số khác bao nhiêu, mà hỏi mass phải di chuyển xa thế nào.",
        "Vì vậy nó phù hợp khi geometry của dữ liệu quan trọng.",
    ]),
    20: ("DROLimitsScene", "scene_20_dro_limits.py", 70, [
        "DRO giả định worst-case trong uncertainty set đại diện cho real shifts.",
        "Nếu mismatch, model tối ưu cho một distribution không xảy ra.",
        "Nếu quá bi quan, model học một bài toán khó không cần thiết.",
    ]),
}

SCENE_FRAMING = {
    1: (
        "Câu hỏi mở đầu là: một mô hình đạt chín mươi chín phần trăm accuracy đã đủ đáng tin khi triển khai hay chưa? Hãy theo dõi sự khác biệt giữa kết quả trong phòng thí nghiệm và hành vi ngoài thực tế.",
        "Vì vậy, accuracy cao chỉ mô tả hiệu quả trên bộ test đã chọn. Độ tin cậy khi triển khai còn phụ thuộc dữ liệu mới có tuân theo cùng quy luật hay không. Ta cần đánh giá model trong những bối cảnh thực sự sẽ gặp.",
    ),
    2: (
        "Bốn thất bại trên màn hình thuộc những lĩnh vực rất khác nhau. Trong cảnh này, hãy tìm điểm chung phía sau robot, camera thể thao, hệ thống y tế và xe tự lái.",
        "Điểm chung không nhất thiết là kiến trúc model kém. Thường thì môi trường triển khai đã tạo ra input, tương quan hoặc nhóm người dùng khác với lúc huấn luyện. Nhận diện mismatch là bước đầu để sửa đúng vấn đề.",
    ),
    3: (
        "Khi model thất bại, phản ứng đầu tiên thường là thay kiến trúc. Nhưng trước khi làm vậy, ta nên hỏi lỗi nằm ở model hay nằm trong cách dữ liệu được tạo ra và thu thập.",
        "Một cách làm data-centric bắt đầu bằng việc truy nguồn samples, kiểm tra các nhóm ẩn và đo sự thay đổi giữa train với deployment. Chỉ sau khi hiểu dữ liệu, ta mới biết cần thêm data, đổi objective hay đổi model.",
    ),
    4: (
        "Để hiểu distribution shift, trước hết ta cần hiểu giả định i.i.d. Hãy hình dung toàn bộ dữ liệu được sinh ra từ cùng một chiếc hộp phân phối.",
        "Điều quan trọng không phải train và test chứa các điểm giống hệt nhau. Điều quan trọng là chúng cùng tuân theo một luật sinh dữ liệu. Khi chiếc hộp thay đổi, kết quả test cũ không còn là bảo chứng đầy đủ.",
    ),
    5: (
        "Bây giờ hãy rời thế giới i.i.d. và quan sát hai đám mây train với target dần tách nhau. Khoảng cách này đại diện cho sự thay đổi ngoài đời.",
        "Khi target đi xa khỏi vùng model từng học, accuracy có thể giảm dù model vẫn dự đoán rất tự tin. Vì thế cần theo dõi drift, đánh giá lại trên dữ liệu target và cập nhật giả định triển khai.",
    ),
    6: (
        "Distribution shift không phải một lỗi duy nhất. Cây phân loại trong cảnh này giúp tách những dạng thay đổi cần các cách xử lý khác nhau.",
        "Trước khi chọn một phương pháp robust, hãy nói rõ ta muốn robust trước loại shift nào. Input đổi, tỷ lệ label đổi và cơ chế dự đoán đổi là ba bài toán khác nhau, không nên được xử lý như một.",
    ),
    7: (
        "Cảnh này minh họa X-shift: vị trí dữ liệu xuất hiện thay đổi, trong khi quy luật liên hệ giữa input và label có thể vẫn giữ nguyên.",
        "Nếu decision rule vẫn đúng, thách thức chính là model chưa bao phủ đủ vùng input mới. Ta có thể cần thu thập mẫu đại diện hơn, điều chỉnh trọng số hoặc thích nghi với target distribution.",
    ),
    8: (
        "Khác với X-shift, Y theo X shift làm thay đổi chính ý nghĩa dự đoán. Cùng một input có thể dẫn tới label khác khi môi trường hoặc nhóm dân số thay đổi.",
        "Đây là loại shift khó hơn vì chỉ mở rộng coverage của X chưa chắc giải quyết được. Model phải nhận biết mechanism nào đang hoạt động, hoặc học riêng cho những môi trường có quan hệ Y theo X khác nhau.",
    ),
    9: (
        "Một bảng training nhìn có vẻ đồng nhất, nhưng thường được ghép từ nhiều bệnh viện, khu vực, thiết bị, người gán nhãn và thời kỳ khác nhau.",
        "Nguồn dữ liệu là thông tin quan trọng để đánh giá model. Nếu bỏ mất source labels, ta cũng mất khả năng phát hiện nhóm yếu, kiểm tra stability và hiểu nguyên nhân performance thay đổi.",
    ),
    10: (
        "Pooling giúp có một dataset lớn và thuận tiện, nhưng đồng thời có thể che khuất cấu trúc quan trọng. Hãy quan sát khi các điểm xám được nhìn qua kính phóng đại.",
        "Các cluster được lộ ra có thể đại diện cho những environments với cơ chế khác nhau. Vì vậy, trước khi train một model trung bình, hãy kiểm tra xem dataset có thực sự là một population đồng nhất hay không.",
    ),
    11: (
        "Hai subpopulation có thể nằm trong cùng dataset nhưng tuân theo hai quan hệ dự đoán khác nhau. Cảnh này cho thấy điều gì xảy ra khi ta ép chúng dùng chung một đường trung bình.",
        "Đường average có thể trông hợp lý trên toàn bộ dữ liệu nhưng lại sai có hệ thống cho từng nhóm. Nhận diện predictive heterogeneity giúp ta thiết kế representation, objective và evaluation phù hợp hơn.",
    ),
    12: (
        "OOD generalization không phải một thuật toán đơn lẻ được thêm vào cuối cùng. Nó là một quy trình xuyên suốt từ collection cho đến deployment.",
        "Mỗi giai đoạn có một câu hỏi riêng: dữ liệu gồm những nhóm nào, model học tín hiệu gì, lỗi tập trung ở đâu và target đã thay đổi thế nào. Kết nối các câu hỏi này mới tạo thành một pipeline robust.",
    ),
    13: (
        "ERM là nền tảng của phần lớn machine learning hiện đại. Trong cảnh này, hãy chú ý cách công thức gom loss của mọi sample thành một giá trị trung bình.",
        "Average là một lựa chọn tối ưu hóa, không phải bảo đảm mọi nhóm đều tốt. Khi dữ liệu không đồng nhất, ta cần xem thêm group risk, worst-case risk và các lát cắt lỗi thay vì chỉ nhìn objective trung bình.",
    ),
    14: (
        "Một con số average đẹp có thể được quyết định gần như hoàn toàn bởi majority group. Biểu đồ này tách kết quả tổng thành hiệu quả trên từng nhóm.",
        "Đánh giá đáng tin cần báo cáo cả phân phối performance, đặc biệt là worst group. Điều này rất quan trọng trong các ứng dụng nơi lỗi trên nhóm nhỏ gây hậu quả lớn dù average toàn bộ vẫn cao.",
    ),
    15: (
        "Ví dụ bò và lạc đà cho thấy model có thể chọn một shortcut rất hiệu quả trên training data. Thay vì nhận diện con vật, nó chỉ cần nhìn background.",
        "Spurious feature hấp dẫn vì dễ học và dự đoán đúng trong môi trường train. Muốn model robust, ta cần environments phá vỡ shortcut, dữ liệu phản ví dụ hoặc objective ưu tiên tín hiệu ổn định hơn.",
    ),
    16: (
        "Nếu tối ưu average chưa đủ, DRO đề xuất chuẩn bị cho một phân phối bất lợi. Đây là cách chuyển từ câu hỏi hiệu quả trung bình sang câu hỏi hiệu quả trong trường hợp xấu.",
        "Sức mạnh của DRO đến từ việc buộc model quan tâm tới những phân phối khó. Nhưng kết quả chỉ hữu ích khi tập phân phối được chọn phản ánh những shift thực tế mà hệ thống có khả năng gặp.",
    ),
    17: (
        "Uncertainty set xác định những phân phối nào được phép đóng vai adversary trong DRO. Bán kính rho điều khiển mức độ thay đổi mà model phải chịu được.",
        "Rho là một giả định cần được hiệu chỉnh bằng kiến thức domain và dữ liệu quan sát. Quá nhỏ sẽ bỏ sót target; quá lớn khiến model hy sinh hiệu quả để chống lại những tình huống không thực tế.",
    ),
    18: (
        "f-divergence mô tả shift bằng cách thay đổi trọng số của những mẫu hoặc nhóm đã có trong support training. Hãy quan sát tỷ lệ hai nhóm thay đổi.",
        "Cách nhìn này phù hợp khi target chủ yếu đổi composition. Tuy nhiên, nó khó biểu diễn những vùng dữ liệu hoàn toàn mới nằm ngoài support, vì vậy cần đối chiếu giả định với loại shift thực tế.",
    ),
    19: (
        "Wasserstein đưa geometry vào việc so sánh hai phân phối. Thay vì chỉ đổi trọng số, nó tính chi phí cần thiết để vận chuyển probability mass từ vị trí này sang vị trí khác.",
        "Khoảng cách vận chuyển có ý nghĩa khi những điểm gần nhau đại diện cho các trạng thái tương tự. Chất lượng của DRO Wasserstein vì thế phụ thuộc mạnh vào metric dùng để định nghĩa khoảng cách trong không gian dữ liệu.",
    ),
    20: (
        "DRO có thể tạo ra một worst-case distribution rất khó, nhưng phân phối đó chưa chắc giống target ngoài đời. Cảnh này đặt Q sao và Q thực cạnh nhau để thấy sự mismatch.",
        "Robustness không chỉ là tối ưu cho trường hợp càng xấu càng tốt. Ta cần tối ưu cho những thay đổi có khả năng xảy ra. Một uncertainty set thực tế quan trọng hơn một worst-case cực đoan nhưng sai hướng.",
    ),
}

SCENE_EXPANSIONS = {
    1: (
        "Hãy chú ý: bộ test thường chỉ là một lát cắt của thế giới. Nó có thể không chứa thời tiết mới, thiết bị mới, nhóm người dùng mới hoặc những tình huống hiếm nhưng quan trọng.",
        "Một model đáng tin không chỉ trả lời đúng nhiều lần. Nó còn phải cho biết khi nào không chắc chắn, duy trì hiệu quả trên các nhóm khác nhau và được giám sát sau khi triển khai.",
    ),
    2: (
        "Trong từng ví dụ, model đã tận dụng một tín hiệu từng hữu ích ở training nhưng trở nên sai lệch ở deployment. Bề ngoài lỗi khác nhau, nhưng cấu trúc nguyên nhân lại khá giống nhau.",
        "Khi điều tra failure, ta nên so sánh dữ liệu trước và sau triển khai, xác định nhóm bị ảnh hưởng, rồi kiểm tra feature hoặc tương quan nào đã thay đổi.",
    ),
    3: (
        "Thêm nhiều dữ liệu cũng chưa chắc giải quyết được nếu dữ liệu mới tiếp tục lặp lại cùng thiên lệch. Điều cần thiết là dữ liệu đúng, bao phủ đúng nhóm và đúng điều kiện sử dụng.",
        "Việc kiểm tra data-generating process giúp biến một câu hỏi mơ hồ thành các giả thuyết có thể đo: source nào khác biệt, subgroup nào yếu và mechanism nào không ổn định.",
    ),
    4: (
        "Chữ độc lập nói rằng mỗi sample được rút mà không phụ thuộc trực tiếp vào sample khác. Chữ cùng phân phối nói rằng train và test cùng đến từ chiếc hộp P của X và Y.",
        "Giả định này rất tiện cho đánh giá thống kê. Tuy nhiên, trong hệ thống thật, dữ liệu thường đến theo thời gian, theo cụm hoặc theo nhiều nguồn nên giả định có thể bị phá vỡ.",
    ),
    5: (
        "Sự tách rời có thể diễn ra từ từ như hành vi người dùng thay đổi theo thời gian, hoặc đột ngột khi hệ thống được đưa sang một quốc gia, bệnh viện hay thiết bị mới.",
        "Một dashboard triển khai tốt cần theo dõi cả input distribution, chất lượng prediction và các nhóm quan trọng. Chờ average accuracy giảm mới phản ứng thường là quá muộn.",
    ),
    6: (
        "X-shift thay đổi nơi dữ liệu xuất hiện. Label shift thay đổi tỷ lệ các lớp. Còn Y theo X shift thay đổi chính quy luật ánh xạ từ input sang kết quả.",
        "Việc gọi đúng tên shift giúp thu hẹp lựa chọn: có lúc reweighting là đủ, có lúc cần adaptation, và có lúc phải học lại mechanism hoặc thu thập label mới.",
    ),
    7: (
        "Ví dụ camera ban đêm cho thấy pixel distribution đổi mạnh dù đối tượng vẫn là đối tượng cũ. Tương tự, dữ liệu dân số mới có thể nằm ở vùng feature mà model ít từng quan sát.",
        "Để xử lý X-shift, ta cần đo coverage và khoảng cách giữa source với target. Nhưng cũng phải kiểm tra giả định quan trọng rằng Y theo X thực sự vẫn ổn định.",
    ),
    8: (
        "Nếu mechanism đổi, một boundary từng tối ưu có thể trở thành boundary sai. Khi đó model không chỉ thiếu ví dụ mới; nó đang sử dụng một quy luật không còn phù hợp.",
        "Dấu hiệu của Y theo X shift thường chỉ lộ ra khi có label target hoặc phân tích subgroup cẩn thận. Đây là lý do monitoring chỉ dựa trên input drift là chưa đủ.",
    ),
    9: (
        "Sau khi merge, cột source thường bị xóa hoặc không được dùng. Nhưng chính cột này có thể giải thích khác biệt về thiết bị đo, quy trình thu thập và population.",
        "Giữ provenance cho phép nhóm phát triển tạo split thực tế hơn, báo cáo performance theo nguồn và dự đoán nguồn nào có nguy cơ tạo shift khi deployment.",
    ),
    10: (
        "Một cluster nhỏ có thể gần như không ảnh hưởng tới loss trung bình, dù model thất bại nghiêm trọng trên cluster đó. Màu xám của pooled data khiến vấn đề này khó nhìn thấy.",
        "Các công cụ clustering, metadata và error slicing giúp khôi phục cấu trúc bị che khuất. Mục tiêu không phải chia nhóm tùy ý, mà tìm những nhóm có hành vi dự đoán khác biệt.",
    ),
    11: (
        "Khi hai đường quan hệ có slope khác nhau, residual của đường trung bình không còn là nhiễu ngẫu nhiên. Chúng chứa dấu hiệu rằng dataset đang trộn nhiều mechanism.",
        "Nếu group label có sẵn, ta có thể đánh giá và học theo group. Nếu không có, cần phát hiện nhóm tiềm ẩn từ pattern của feature, label và lỗi dự đoán.",
    ),
    12: (
        "Ở collection, ta ghi lại source và coverage. Ở training, ta kiểm tra shortcut và môi trường. Ở evaluation, ta đo worst group, stability và calibration.",
        "Sau deployment, monitoring phải nối performance drop với loại shift cụ thể. Nhờ vậy, phản ứng có thể là thu data, cập nhật model hoặc thay quy trình thay vì đoán mò.",
    ),
    13: (
        "Mỗi sample đóng góp một phần vào tổng loss, nên nhóm có nhiều mẫu sẽ có tiếng nói lớn hơn. Nhóm nhỏ có thể bị hy sinh nếu điều đó làm average giảm.",
        "ERM không sai; nó tối ưu chính xác objective được giao. Vấn đề là objective trung bình có thể không phản ánh yêu cầu an toàn, công bằng hoặc robustness của ứng dụng.",
    ),
    14: (
        "Ví dụ số học cho thấy majority gần như quyết định con số tổng. Một cải thiện rất nhỏ trên majority có thể che khuất một suy giảm lớn trên minority.",
        "Ngoài accuracy theo nhóm, ta nên xem số lượng mẫu, confidence, loại lỗi và mức độ nghiêm trọng. Một nhóm nhỏ không đồng nghĩa với một rủi ro nhỏ.",
    ),
    15: (
        "Trong training environment, cỏ và sa mạc là tín hiệu dự đoán mạnh, thậm chí dễ học hơn hình dáng con vật. Vì vậy model có lý do thống kê để chọn shortcut.",
        "Đưa bò sang bãi biển là một phép thử phản ví dụ. Nó giữ đối tượng nhưng thay background, nhờ đó cho thấy model đang dựa vào feature nào để ra quyết định.",
    ),
    16: (
        "Trong trò chơi min-max, adversary tìm cách tăng loss còn model tìm cách giảm loss cao nhất đó. Kết quả thường cân bằng hơn giữa các tình huống khó.",
        "Tuy nhiên, adversary chỉ được chọn Q trong vùng ta định nghĩa. Nếu vùng này không chứa shift thật hoặc chứa quá nhiều shift vô lý, robustness thu được sẽ lệch mục tiêu.",
    ),
    17: (
        "Ta có thể xem uncertainty set như bản mô tả những tương lai mà model cần chuẩn bị. Hình dạng, metric và bán kính của vùng đều mã hóa giả định của người thiết kế.",
        "Hiệu chỉnh rho nên dựa trên shift lịch sử, kiến thức chuyên gia và validation ngoài distribution. Không nên chọn rho chỉ vì nó tạo ra một công thức thuận tiện.",
    ),
    18: (
        "Density ratio lớn hơn một làm một vùng quan trọng hơn dưới Q, còn nhỏ hơn một làm vùng đó nhẹ đi. Support cơ bản vẫn là support đã quan sát trong P.",
        "Nếu target chỉ đổi tỷ lệ người trẻ và người già, reweighting có thể hợp lý. Nếu target xuất hiện một nhóm hoàn toàn mới, ambiguity set này có thể bỏ sót.",
    ),
    19: (
        "Trong optimal transport, mỗi mũi tên mang một lượng mass và chịu chi phí theo quãng đường. Tổng chi phí nhỏ nhất trở thành khoảng cách giữa hai phân phối.",
        "Metric cần phản ánh ý nghĩa domain. Nếu khoảng cách giữa hai điểm không tương ứng với mức độ thay đổi thực tế, Wasserstein ball cũng sẽ mô tả sai các target khả dĩ.",
    ),
    20: (
        "Một adversary toán học có thể tập trung vào hướng làm loss tăng nhanh nhất, trong khi deployment lại thay đổi theo một hướng khác do con người, thiết bị hoặc chính sách.",
        "Vì vậy, đánh giá DRO cần so sánh với các shift có thật và các stress test có ý nghĩa. Worst-case chỉ hữu ích khi chữ worst gắn với thế giới mà hệ thống sẽ hoạt động.",
    ),
}


VISUAL_NARRATIONS = {
    1: [(5.5, "Mở đầu là một kết quả rất đẹp: test accuracy đạt chín mươi chín phẩy một phần trăm."),
        (18, "Dashboard cũng hoàn hảo: loss giảm đều, validation ổn định, mọi chỉ số đều phát tín hiệu xanh."),
        (33, "Nhưng câu hỏi quan trọng là: con số này đang đúng trong thế giới nào?"),
        (47.5, "Train và test gần nhau nên validation xác nhận model hoạt động tốt trên dữ liệu quen thuộc."),
        (67, "Khi chuyển sang deployment, ánh sáng, camera, bệnh viện hoặc người dùng có thể thay đổi. Phân phối mới không còn giống training."),
        (84, "Lúc đó, con số đẹp trong phòng thí nghiệm bắt đầu nứt. Test accuracy cao chưa chắc đồng nghĩa với độ tin cậy ngoài đời."),
        (98, "Muốn tin model, ta phải hiểu dữ liệu deployment đã khác training như thế nào.")],
    2: [(9.8, "Bốn thẻ trên màn hình là bốn failure ngoài đời: robot bị kẹt, camera thể thao theo nhầm đối tượng, AI y tế học nhầm tín hiệu và xe tự lái hiểu sai bối cảnh."),
        (29, "Dù thuộc các lĩnh vực khác nhau, những lỗi này đều xuất hiện sau khi model rời môi trường training."),
        (43.5, "Vậy điểm chung là gì? Không nhất thiết model quá yếu; có thể dữ liệu đầu vào và các tương quan đã thay đổi."),
        (72.5, "Kết luận: nhiều thất bại bắt đầu từ sự lệch nhau giữa dữ liệu huấn luyện và dữ liệu khi triển khai.")],
    3: [(4, "Khi model thất bại, ta thường lập tức nghĩ đây là một model problem."),
        (22.5, "Hai hướng xử lý xuất hiện: thay model, hoặc nhìn lại dữ liệu."),
        (32.0, "Thêm layer, regularization hay nhiều mẫu hơn chưa chắc sửa được thiên lệch đang có."),
        (51.5, "Góc nhìn data-centric kiểm tra sources, subpopulations, mechanisms và shifts bên trong dataset."),
        (68, "Trước khi đổi model, hãy kiểm tra chính data-generating process.")],
    4: [(4, "Chiếc hộp này đại diện cho một phân phối chung, P của X và Y."),
        (20, "Từ cùng chiếc hộp, các mẫu được rút vào hai rổ train và test."),
        (40, "Hai tập không chứa các điểm giống hệt nhau, nhưng cùng tuân theo một luật sinh dữ liệu."),
        (63, "Đó là ý nghĩa của độc lập và cùng phân phối."),
        (82.8, "Công thức xác nhận P train bằng P test. Đây là giả định i.i.d. quen thuộc.")],
    5: [(4, "Ban đầu, train và test cùng nằm trong một vùng nên giả định i.i.d. có vẻ hợp lý."),
        (53.5, "Khi target cloud dịch chuyển, khoảng cách với vùng training ngày càng lớn."),
        (63.5, "Accuracy bắt đầu giảm khi target đi ra khỏi vùng model từng quan sát."),
        (73.5, "Phân phối train và target giờ không còn bằng nhau."),
        (89.0, "Distribution shift bắt đầu khi train và target tách khỏi nhau.")],
    6: [(4, "Distribution shift là tên chung ở gốc cây."),
        (18, "Từ đó, cây tách thành ba nhánh thay đổi khác nhau."),
        (32.5, "X-shift đổi phân phối input. Label shift đổi tỷ lệ nhãn. Y theo X shift đổi cơ chế dự đoán."),
        (50, "Ba loại shift có thể trông giống nhau qua performance drop, nhưng cần cách xử lý khác nhau."),
        (64.6, "Trước khi chọn phương pháp robust, phải trả lời rõ: robust trước loại shift nào?")],
    7: [(4, "X-shift nghĩa là phân phối của input X thay đổi."),
        (17, "Đường màu xanh biểu diễn phân phối source ban đầu."),
        (32.7, "Đường màu vàng dịch sang vùng input mới, cho thấy target xuất hiện ở nơi khác."),
        (51, "Decision boundary vẫn giữ nguyên vì quy luật Y theo X có thể chưa thay đổi."),
        (71.8, "X-shift thay đổi nơi dữ liệu xuất hiện, không nhất thiết thay đổi ý nghĩa của dữ liệu.")],
    8: [(4, "Y theo X shift thay đổi chính cơ chế liên hệ giữa input và label."),
        (20, "Panel source cho thấy một cơ chế dự đoán đang hoạt động trong môi trường ban đầu."),
        (39.1, "Target có input tương tự, nhưng decision boundary bắt đầu khác source."),
        (62.0, "Khi boundary xoay, cùng một X có thể dẫn tới dự đoán Y khác."),
        (87.6, "Vì vậy Y theo X shift làm thay đổi ý nghĩa của dữ liệu.")],
    9: [(5.2, "Training data thường đến từ nhiều nguồn: bệnh viện, người dùng, khu vực, cảm biến và thời kỳ."),
        (21, "Các nguồn nhìn riêng biệt trước khi được đưa vào cùng một pipeline thu thập."),
        (42.7, "Sau khi merge, chúng trở thành một bảng training duy nhất."),
        (58, "Những điểm trong bảng vẫn mang cấu trúc và dấu vết từ nguồn gốc khác nhau."),
        (74, "Một dataset thường là hỗn hợp, không phải một population đồng nhất.")],
    10: [(4, "Khi pooling, tất cả điểm dữ liệu được tô cùng màu và trông như một population duy nhất."),
         (18, "Đám điểm xám làm các nhóm bên trong gần như biến mất."),
         (40.5, "Kính phóng đại bắt đầu quét qua dữ liệu và làm lộ cấu trúc bị che khuất."),
         (57, "Các cluster màu có thể tương ứng với bệnh viện, vùng địa lý hoặc nhóm người dùng khác nhau."),
         (78, "Pooling có thể che giấu những environments quan trọng.")],
    11: [(4.2, "Trước tiên ta chỉ thấy một tập điểm pooled trên cùng hệ trục."),
         (23.0, "Một đường regression trung bình được fit qua toàn bộ dữ liệu."),
         (35.0, "Các residual lớn cho thấy đường trung bình không giải thích tốt mọi điểm."),
         (45.0, "Khi màu nhóm được tiết lộ, hai subpopulation riêng biệt xuất hiện."),
         (51.4, "Mỗi nhóm có một đường regression và một mechanism khác nhau."),
         (77.9, "Một model trung bình có thể che giấu nhiều cơ chế dự đoán.")],
    12: [(3.9, "Khái quát hóa ngoài phân phối cần được nhìn như một quy trình hoàn chỉnh."),
         (18, "Ở bước thu thập, câu hỏi là dữ liệu đến từ đâu và có bao phủ đủ nhóm hay không."),
         (30, "Ở bước huấn luyện và đánh giá, ta kiểm tra môi trường, độ ổn định và từng lát lỗi."),
         (46.5, "Hạt sáng đi xuyên quy trình, minh họa thông tin phải được theo dõi qua mọi giai đoạn."),
         (73.0, "Khái quát hóa ngoài phân phối là một quy trình, không phải một thuật toán đơn lẻ.")],
    13: [(6, "Công thức ERM tối thiểu hóa tổng loss trên dữ liệu training."),
         (18, "Phần được tô vàng là phép lấy trung bình trên tất cả mẫu."),
         (37, "Biểu đồ minh họa loss của sáu mẫu, mỗi mẫu nhận cùng trọng số một trên n."),
         (55, "Đường ngang là loss trung bình mà ERM đang tối ưu."),
         (66, "Nhưng average có thể bỏ qua một nhóm ẩn có loss cao."),
         (72.8, "ERM tối ưu loss trung bình, không bảo đảm mọi nhóm đều tốt.")],
    14: [(5.9, "Con số lớn chín mươi lăm phần trăm là average accuracy nhìn rất thuyết phục."),
         (18, "Khi tách thành từng nhóm, bức tranh trở nên khác hẳn."),
         (31, "Majority group đạt accuracy cao và chi phối đường average."),
         (42, "Worst group chỉ đạt bốn mươi ba phần trăm dù kết quả tổng vẫn đẹp."),
         (59, "Trong các ứng dụng quan trọng, nhóm nhỏ có thể là nhóm chịu rủi ro lớn nhất."),
         (74, "Average performance có thể che giấu local failure.")],
    15: [(4.9, "Trong training, bò thường đi cùng nền cỏ và lạc đà thường đi cùng sa mạc."),
         (18, "Background được làm sáng vì đây là shortcut dễ học."),
         (31, "Hình dáng con vật mới là tín hiệu ổn định hơn, nhưng khó học hơn."),
         (45, "Đến test time, con bò xuất hiện trên một background mới: bãi biển."),
         (51.8, "Model dựa vào background nên đưa ra dự đoán sai."),
         (67, "Đây là spurious correlation: đúng trong training nhưng không ổn định khi environment đổi."),
         (81.2, "Shortcut của training environment tạo ra failure ngoài distribution.")],
    16: [(6.4, "ERM hỏi model nào tốt nhất trên training distribution trung bình."),
         (19, "Giới hạn của câu hỏi này là nó chỉ tập trung vào một phân phối."),
         (31, "DRO biến objective thành tối ưu trên phân phối xấu nhất trong một tập được chọn."),
         (40.2, "Phần supremum cho adversary quyền chọn Q làm loss cao nhất."),
         (55, "Trong trò chơi hai phía, model giảm loss còn adversary tìm tình huống khó."),
         (73.8, "DRO chuẩn bị model cho một họ các shift bất lợi đã được định nghĩa.")],
    17: [(4.5, "Không gian này chứa nhiều phân phối có thể xảy ra."),
         (15, "Điểm P train là phân phối quan sát được khi huấn luyện."),
         (25, "Vòng tròn uncertainty set chứa các Q nằm trong bán kính rho."),
         (39, "Khi rho tăng hoặc giảm, phạm vi các shift model phải chịu cũng thay đổi."),
         (47.8, "Q sao là phân phối trong vùng làm loss lớn nhất."),
         (62, "Rho quá nhỏ bỏ sót shift thật; rho quá lớn tạo worst-case quá cực đoan."),
         (80, "Uncertainty set là giả định cốt lõi của DRO.")],
    18: [(8, "f-divergence so sánh P và Q thông qua density ratio d Q trên d P."),
         (32.0, "Hai biểu đồ cho thấy tỷ lệ nhóm trong P train và Q target."),
         (28.0, "Mũi tên reweight thay đổi trọng số giữa nhóm người già và người trẻ."),
         (48.5, "Density ratio cho biết mỗi vùng được tăng hoặc giảm trọng số bao nhiêu."),
         (64, "Support vẫn là những vùng đã có trong dữ liệu training."),
         (79, "f-divergence mô tả shift bằng cách reweight support hiện có.")],
    19: [(6.3, "Khác với f-divergence chỉ reweight, Wasserstein còn nhìn vào geometry."),
         (24.5, "Hai phân phối xuất hiện ở các vị trí khác nhau trên cùng không gian."),
         (36.5, "Các mũi tên cho thấy probability mass phải được vận chuyển từ source sang target."),
         (49, "Mỗi chuyến vận chuyển chịu chi phí theo lượng mass và quãng đường."),
         (58, "Tổng chi phí vận chuyển nhỏ nhất tạo thành Wasserstein distance."),
         (72, "Công thức tối ưu transport plan có tổng chi phí thấp nhất."),
         (79, "Wasserstein phù hợp khi geometry của dữ liệu mang ý nghĩa.")],
    20: [(4.5, "Điểm bắt đầu là phân phối training P."),
         (17.5, "Uncertainty ball mô tả những phân phối DRO cho là có thể xảy ra."),
         (24, "Q sao nằm trong ball và là worst-case mà model đang tối ưu."),
         (32.7, "Nhưng phân phối thật khi triển khai lại nằm theo một hướng khác."),
         (46, "Mũi tên đỏ cho thấy trường hợp xấu nhất trên giấy không trùng với dịch chuyển thật."),
         (59, "Có hai lỗi chính: vùng bất định sai hướng, hoặc mô hình trở nên quá bi quan."),
         (71.9, "Phương pháp này chỉ hữu ích khi vùng bất định phản ánh đúng các dịch chuyển thực tế.")],
}

VISUAL_FILLERS = {
    1: [(26, "Các đường cong và chỉ số trên dashboard chỉ phản ánh dữ liệu validation đã được chuẩn bị trước."),
        (40, "Màn hình đang đặt kết quả trong phòng thí nghiệm cạnh câu hỏi về độ tin cậy khi triển khai."),
        (57, "Ở giai đoạn này, train và test vẫn chia sẻ gần như cùng một data-generating process."),
        (76, "Deploy cloud màu đỏ biểu diễn những tình huống mà model chưa được kiểm tra đầy đủ."),
        (92, "Vết nứt nhấn mạnh khoảng cách giữa thành tích đo được và độ tin cậy thực tế.")],
    2: [(23, "Mỗi hệ thống đều hoạt động tốt trong điều kiện quen thuộc trước khi gặp một bối cảnh bất ngờ."),
        (59, "Câu hỏi điều tra đúng là dữ liệu nào đã thay đổi, thay vì chỉ hỏi kiến trúc nào cần lớn hơn."),
        (82, "Phân tích nguồn mismatch giúp lựa chọn đúng cách thu thập dữ liệu và đánh giá lại model.")],
    3: [(27.5, "Hai chiếc hộp nhắc ta rằng lỗi dự đoán có thể đến từ cả thuật toán lẫn dữ liệu."),
        (58, "Nhìn sâu vào data box giúp phát hiện nguồn, nhóm ẩn và cơ chế đang bị trộn lẫn."),
        (80, "Chẩn đoán đúng nguyên nhân giúp tránh sửa model trong khi vấn đề thực sự nằm ở dữ liệu.")],
    4: [(30, "Các mũi tên cho thấy cả hai tập đều nhận mẫu từ cùng một nguồn."),
        (11, "Giả định cốt lõi là chiếc hộp phân phối này không thay đổi giữa lúc huấn luyện và kiểm tra."),
        (52, "Sự độc lập nằm ở quá trình rút mẫu, còn cùng phân phối nằm ở chiếc hộp sinh dữ liệu."),
        (72, "Nếu luật sinh dữ liệu đổi, bảo đảm từ test set cũ sẽ không còn nguyên vẹn."),
        (93, "i.i.d. là một giả định mạnh và cần được kiểm tra trước khi tin vào kết quả test.")],
    5: [(58.5, "Khoảng cách giữa hai cloud là trực giác trực quan cho mức độ khác biệt giữa source và target."),
        (68.5, "Các mức accuracy giảm dần cho thấy performance có thể suy yếu theo độ lớn của shift."),
        (81.5, "Dấu khác nhau trong công thức xác nhận target không còn thuộc phân phối training."),
        ],
    6: [(28.0, "Mỗi nhánh của cây trả lời một câu hỏi khác nhau về phần nào của phân phối đã đổi."),
        (11, "Tên gọi chung này cần được tách nhỏ trước khi ta có thể chọn cách xử lý phù hợp."),
        (42, "Việc phân loại shift giúp loại bỏ những phương pháp không phù hợp với nguyên nhân."),
        (57, "Quan sát ba nhánh cạnh nhau cho thấy cùng một dấu hiệu suy giảm có thể bắt nguồn từ các thay đổi rất khác."),
        (74, "Một tuyên bố robustness chỉ có ý nghĩa khi nêu rõ loại shift được xét.")],
    7: [(24, "Source distribution tập trung ở vùng model đã quan sát trong training."),
        (10, "Trên hệ trục input, ta sẽ theo dõi vị trí của phân phối thay đổi như thế nào."),
        (42, "Target distribution dịch chuyển nhưng vẫn được so sánh trên cùng không gian input."),
        (61, "Boundary giữ nguyên minh họa giả định mechanism dự đoán vẫn ổn định."),
        (82, "Nếu mechanism cũng đổi, bài toán sẽ không còn chỉ là X-shift.")],
    8: [(29, "Source panel cung cấp quy luật ban đầu giữa feature và label."),
        (12, "Công thức phía trên nhấn mạnh rằng cùng một X, quy luật P của Y theo X có thể đổi giữa source và target."),
        (50, "Hai panel có thể trông gần giống về input nhưng khác nhau ở cách phân chia label."),
        (83, "Sự khác biệt giữa hai đường biên là lý do model học từ source không còn đáng tin trên target."),
        (76, "Boundary mới cho thấy model cũ đang áp dụng sai cơ chế cho target."),
        (98, "Phát hiện loại shift này thường cần label target hoặc phân tích subgroup.")],
    9: [(32, "Mỗi source có thể dùng thiết bị, quy trình và population khác nhau."),
        (14, "Các biểu tượng nguồn nhắc rằng mỗi mẫu luôn đi kèm một bối cảnh thu thập cụ thể."),
        (50, "Việc merge làm mất vẻ khác biệt bên ngoài nhưng không xóa khác biệt thống kê."),
        (66, "Các cụm điểm minh họa cấu trúc nguồn vẫn tồn tại trong bảng pooled."),
        (82, "Giữ metadata nguồn giúp đánh giá performance theo từng environment.")],
    10: [(29, "Khi chỉ nhìn pooled data, model được huấn luyện như thể mọi điểm đến từ cùng một cơ chế."),
         (49, "Kính lúp đại diện cho bước phân tích nhằm tìm lại environments bị ẩn."),
         (67, "Màu sắc khác nhau cho thấy pooled dataset thực chất chứa nhiều subpopulation."),
         (86, "Phát hiện cấu trúc này giúp đánh giá đúng các nhóm có nguy cơ thất bại.")],
    11: [(29.0, "Nếu chỉ nhìn màu xám, đường trung bình dường như là lựa chọn hợp lý."),
        (39, "Residual có cấu trúc là dấu hiệu lỗi không phải chỉ do nhiễu ngẫu nhiên."),
        (58, "Khi tách nhóm, cấu trúc từng cụm giải thích vì sao một đường chung tạo ra sai số có hệ thống."),
        (64, "Hai đường riêng fit tốt hơn vì chúng phản ánh hai quan hệ Y theo X khác nhau."),
         (88, "Group membership trong trường hợp này chứa thông tin dự đoán quan trọng.")],
    12: [(23, "Mỗi giai đoạn cần lưu lại thông tin để giai đoạn tiếp theo có thể kiểm tra độ vững chắc."),
         (38, "Đánh giá không chỉ đo trung bình, mà còn đo từng lát lỗi, độ ổn định và độ hiệu chỉnh."),
         (58, "Bước giám sát sau triển khai nối sự suy giảm hiệu quả với đúng loại dịch chuyển đã xảy ra."),
         (80, "Kết nối các bước giúp nhóm phát triển phản ứng đúng khi hệ thống suy giảm.")],
    13: [(27, "Hệ số một trên n khiến mỗi sample đóng góp cùng trọng số vào objective."),
         (46, "Các cột cao thấp khác nhau nhưng đều được gộp vào cùng một phép trung bình."),
         (61, "Nhóm có nhiều mẫu sẽ tác động mạnh hơn tới objective tổng."),
         (82, "Vì vậy cần xem thêm group risk và worst-case risk bên cạnh ERM.")],
    14: [(25, "Các cột cho thấy average là kết quả pha trộn performance của nhiều nhóm."),
         (50, "Nhóm tệ nhất được tô đỏ để tách failure bị con số tổng che khuất."),
         (66, "Mức độ nghiêm trọng của lỗi không tỷ lệ đơn giản với kích thước nhóm."),
         (82, "Báo cáo worst-group performance giúp đánh giá rủi ro minh bạch hơn.")],
    15: [(25, "Model có động lực chọn background vì tín hiệu này đơn giản và dự đoán đúng trên train."),
         (39, "So sánh shape với background giúp phân biệt feature ổn định và feature giả."),
         (59, "Đường tín hiệu đỏ cho thấy dự đoán sai đang đi qua shortcut background."),
         (75, "Một phản ví dụ thay background là cách trực tiếp để phát hiện shortcut."),
         (91, "Robust model cần dựa vào tín hiệu còn đúng khi môi trường thay đổi.")],
    16: [(25, "Phép biến đổi objective thay average risk bằng worst-case risk."),
         (47, "Adversary chỉ được chọn các phân phối nằm trong tập uncertainty đã định nghĩa."),
         (64, "Hai mũi tên minh họa vòng lặp model chọn theta và adversary chọn Q."),
         (82, "Chất lượng DRO phụ thuộc trực tiếp vào họ shift được đưa vào trò chơi.")],
    17: [(20, "P train là tâm tham chiếu để đo khoảng cách tới các phân phối khác."),
         (32, "Bán kính rho mã hóa mức độ thay đổi mà model cần chuẩn bị."),
         (55, "Worst-case Q sao vẫn phải nằm bên trong uncertainty set."),
         (71, "So sánh rho nhỏ và rho lớn cho thấy sự đánh đổi giữa bỏ sót và quá bi quan."),
         (84, "Một uncertainty set tốt phải phản ánh shift có khả năng xảy ra.")],
    18: [(36.0, "P train và Q target dùng cùng các nhóm nhưng phân bổ probability mass khác nhau."),
        (41, "Reweighting không tạo ra vùng support hoàn toàn mới."),
        (56, "Density ratio lớn hơn một tăng tầm quan trọng của một nhóm dưới target."),
        (71, "Trong hình minh họa này, target chỉ phân bổ lại khối lượng xác suất giữa những nhóm đã quan sát."),
        (87, "Giới hạn quan trọng là phương pháp không mô tả trực tiếp những vùng support hoàn toàn mới.")],
    19: [(29.0, "Khoảng cách giữa các vị trí quyết định chi phí, nên hai thay đổi cùng trọng lượng vẫn có thể rất khác nhau."),
         (54, "Các mũi tên ghép source với target tạo thành một transport plan cụ thể."),
         (65, "Bài toán tìm plan có tổng chi phí nhỏ nhất, thay vì chọn một cách vận chuyển tùy ý."),
         (87, "Vì có xét khoảng cách, Wasserstein giữ lại thông tin hình học mà phép reweight đơn thuần bỏ qua.")],
    20: [(39, "Hình vẽ đặt Q sao và phân phối thật cạnh nhau để làm rõ giả định đang lệch hướng."),
         (78, "Kết luận là độ vững chắc chỉ có giá trị khi tập bất định phản ánh đúng các thay đổi có thể xảy ra.")],
}

VISUAL_DENSE_FILLERS = {
    1: [(12, "Con số lớn trên màn hình cố ý tạo cảm giác an toàn trước khi ta nhìn sang bối cảnh dữ liệu.")],
    2: [(38, "Các dấu cảnh báo cho thấy failure không nằm ở một ví dụ đơn lẻ mà lặp lại qua nhiều hệ thống."),
        (52, "Trọng tâm chuyển từ triệu chứng sang nguyên nhân dữ liệu."),
        (64, "Khi môi trường triển khai khác lúc huấn luyện, cùng một mô hình có thể gặp dữ liệu và shortcut chưa từng được kiểm tra."),
        (78, "Montage gom nhiều failure thành một bài học về distribution shift."),
        (89, "Phần kết giữ lại thông điệp: muốn sửa đúng, trước hết phải truy ra nguồn mismatch.")],
    3: [(10.5, "Hai khối trên màn hình nhắc ta rằng lỗi có thể đến từ cả mô hình lẫn dữ liệu."),
        (17.5, "Hai chữ model và data được đặt cạnh nhau để nhắc rằng chẩn đoán sai sẽ dẫn tới cách sửa sai."),
        (40.0, "Nếu nguyên nhân nằm trong dữ liệu, thay kiến trúc chỉ làm ta sửa nhầm chỗ."),
        (46.5, "Mũi tên giữa hai hộp nhấn mạnh rằng model và dữ liệu không thể được tách rời khi phân tích lỗi."),
        (64, "Các mục trong data box là dấu vết cần kiểm tra trước khi đổi model."),
        (75, "Insight ở cuối cảnh đang chuẩn bị cho toàn bộ phần tiếp theo: nhìn robust learning từ phía dữ liệu."),
        (86, "Nếu data-generating process lệch, thêm tham số có thể chỉ làm model học shortcut mạnh hơn.")],
    4: [(24, "Train và test là hai rổ khác nhau, nhưng cùng nhận mẫu từ một cơ chế sinh dữ liệu."),
        (34, "Các mũi tên nói hai tập giống về luật thống kê phía sau."),
        (48, "Đây là lý do test set i.i.d. thường cho ta cảm giác đánh giá rất chắc chắn."),
        (57, "Khi chiếc hộp giữ nguyên, sai số test phản ánh khá tốt cùng thế giới triển khai."),
        (66.5, "Lập luận này phụ thuộc vào giả định chiếc hộp P không đổi."),
        (88, "Công thức ở cuối chỉ đúng khi cả train và test cùng quay quanh một phân phối chung.")],
    5: [(18.0, "Ở đoạn đầu, hai cloud còn gần nhau nên kết quả validation vẫn có vẻ đáng tin."),
        (11.0, "Công thức trên màn hình đang giả định train và test vẫn cùng một thế giới dữ liệu."),
        (26.0, "Train và test vẫn nằm trong vùng quen thuộc, nên dấu hiệu cảnh báo chưa thật sự rõ."),
        (32.0, "Màn hình accuracy lúc này vẫn còn đẹp vì target chưa thật sự rời xa vùng training."),
        (38.0, "Con số accuracy vẫn giữ màu xanh, nên nếu chỉ nhìn chỉ số ta rất dễ yên tâm quá sớm."),
        (43.0, "Khoảng lặng trước khi dịch chuyển cho thấy vấn đề chưa nằm ở con số, mà nằm ở phân phối sắp thay đổi."),
        (49.0, "Ngay trước khi target dịch chuyển, điểm yếu của validation cũ vẫn còn bị che khuất."),
        (77.5, "Dấu bằng bị phá vỡ là khoảnh khắc trực quan nhất của distribution shift."),
        (85.5, "Khoảng cách tăng thì performance drop trở thành hệ quả của dữ liệu mới.")],
    6: [(82, "Cây phân loại này sẽ là bản đồ để chọn đúng kỹ thuật robust ở những phần sau.")],
    7: [(66, "Đường biên đứng yên giúp tách X-shift khỏi trường hợp cơ chế dự đoán đổi."),
        (86.5, "Cảnh kết lại bằng ranh giới: nếu Y theo X cũng đổi, ta cần một khái niệm shift khác.")],
    8: [(35, "Ở source panel, đường biên quyết định đang mô tả cơ chế gán nhãn của môi trường ban đầu."),
        (46, "Đây là điểm nguy hiểm: model nhìn thấy X quen thuộc nhưng ý nghĩa của X đã đổi."),
        (57, "Đường biên xoay là dấu hiệu cơ chế dự đoán target không còn giống source."),
        (70, "So với X-shift, loại shift này khó hơn vì cần hiểu sự thay đổi của quan hệ Y theo X.")],
    9: [(28, "Trước khi merge, mỗi source vẫn mang population và quy trình đo riêng."),
        (38, "Khi đi vào bảng chung, source label có thể biến mất khỏi mắt người huấn luyện.")],
    10: [(12, "Dòng mô tả trên màn hình đang gom mọi sample thành một khối, trước khi các điểm dữ liệu thật sự hiện ra."),
         (25, "Train ngay trên khối gộp sẽ tối ưu một average che các nhóm bên trong."),
         (37, "Kính lúp là thao tác audit dữ liệu, không phải thay đổi model."),
         (74, "Các cụm màu là bằng chứng rằng pooled dataset vẫn chứa nhiều môi trường ẩn.")],
    11: [(13.0, "Các điểm xám ban đầu che mất thông tin nhóm, nên đường trung bình trông có vẻ hợp lý."),
         (72, "Sau khi tách màu, ta thấy lỗi trước đó có cấu trúc chứ không phải nhiễu ngẫu nhiên."),
         (84, "Group membership có thể là tín hiệu dự đoán, không chỉ metadata phụ."),
         (94, "Cảnh này nối trực tiếp tới predictive heterogeneity ở các phần sau.")],
    12: [(12.0, "Quy trình trên màn hình nhấn mạnh học vững chắc bắt đầu từ bước thu thập, không phải chỉ ở huấn luyện."),
         (54, "Hạt sáng cho thấy thông tin cần được truyền xuyên suốt quy trình."),
         (66, "Nếu mất thông tin nguồn ở giữa quy trình, bước đánh giá sẽ khó giải thích vì sao hiệu quả suy giảm."),
         (85.5, "Kết luận là độ vững chắc cần một quy trình có phản hồi liên tục sau khi triển khai.")],
    13: [(13, "Công thức được giữ lâu vì chữ average là điểm then chốt của ERM."),
         (22, "Mọi mẫu cùng trọng số làm objective gọn nhưng dễ che subgroup yếu."),
         (43, "Sáu cột loss bị gom lại thành một con số duy nhất."),
         (77, "Takeaway chuẩn bị cho câu hỏi: average đẹp có thể giấu failure nào?"),
         (87, "Đây là lý do ta cần nhìn thêm group risk thay vì chỉ báo cáo training objective.")],
    14: [(13, "Con số trung bình được phóng lớn để cho thấy nó dễ thuyết phục đến mức nào."),
         (38, "Đường average đi ngang qua biểu đồ nhưng không đại diện công bằng cho từng nhóm.")],
    15: [(12, "Hai background được đặt cạnh con vật để làm shortcut trở nên dễ nhìn ngay từ đầu.")],
    16: [(14, "Công thức ERM ở đây là điểm xuất phát: tối ưu tốt trên một phân phối trung bình.")],
    17: [(10, "Không gian phân phối được giữ lại để ta thấy P train chỉ là một điểm tham chiếu.")],
    18: [(4, "Cảnh mở bằng công thức để nhấn mạnh f-divergence đo shift qua tỷ lệ mật độ."),
         (17, "Density ratio cho biết target đặt nặng vùng nào hơn so với training.")],
    19: [(14, "Khác biệt chính nằm ở khoảng cách trong feature space, không chỉ ở trọng số xác suất."),
         (43, "Các mũi tên vận chuyển biến geometry thành chi phí cụ thể trên màn hình.")],
    20: [(13.8, "Tâm phân phối huấn luyện vừa xuất hiện như điểm tham chiếu trong không gian phân phối."),
         (54, "Khi mũi tên đỏ xuất hiện, ta thấy Q sao không còn đại diện cho triển khai thật."),
         (67, "Hai ô bên phải tách rõ hai vấn đề: sai hướng dịch chuyển và quá bi quan.")],
}

SCENE_OPENINGS = {
    1: "Phần một. Độ chính xác cao, nhưng thất bại ngoài đời.",
    2: "Phần hai. Chuỗi ví dụ thất bại và nguyên nhân chung.",
    3: "Phần ba. Lỗi do mô hình hay do dữ liệu.",
    4: "Phần bốn. Giả định độc lập và cùng phân phối.",
    5: "Phần năm. Khi tập huấn luyện và tập kiểm tra tách nhau.",
    6: "Phần sáu. Phân loại các dạng dịch chuyển phân phối.",
    7: "Phần bảy. Dịch chuyển phân phối đầu vào.",
    8: "Phần tám. Dịch chuyển quan hệ giữa đầu vào và nhãn.",
    9: "Phần chín. Dữ liệu đến từ nhiều nguồn khác nhau.",
    10: "Phần mười. Ảo giác của dữ liệu gộp.",
    11: "Phần mười một. Các nhóm ẩn trong dữ liệu.",
    12: "Phần mười hai. Góc nhìn quy trình tổng thể.",
    13: "Phần mười ba. Công thức tối ưu sai số trung bình.",
    14: "Phần mười bốn. Rủi ro trung bình che giấu nhóm tệ nhất.",
    15: "Phần mười lăm. Tương quan giả giữa con vật và phông nền.",
    16: "Phần mười sáu. Trực giác về tối ưu trong trường hợp xấu nhất.",
    17: "Phần mười bảy. Tập bất định quanh phân phối huấn luyện.",
    18: "Phần mười tám. Đo dịch chuyển bằng tỷ lệ mật độ.",
    19: "Phần mười chín. Khoảng cách vận chuyển giữa hai phân phối.",
    20: "Phần hai mươi. Giới hạn của tối ưu trong trường hợp xấu nhất.",
}


def scene_01_20_entries():
    entries = {}
    for scene_num, (class_name, file_name, _, _) in SCENE_01_20_NARRATIONS.items():
        entries[scene_num] = {
            "class": class_name,
            "file": file_name,
            "duration": 80,
            "voice_segments": sorted(
                [
                    (0.0, SCENE_OPENINGS[scene_num]),
                    *VISUAL_NARRATIONS[scene_num],
                    *VISUAL_FILLERS[scene_num],
                    *VISUAL_DENSE_FILLERS.get(scene_num, []),
                ],
                key=lambda item: item[0],
            ),
            "explicit_timing": True,
        }
    return entries
